# ====================================================================
# Mosquitto
# ====================================================================
# Connection String: 
# ====================================================================
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    hostname: mqtt   
    network_mode: host
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    environment:
      - TZ=America/Chicago
    volumes:      
      - ./config:/mosquitto/config
      - ./volumes/data:/mosquitto/data
      - ./volumes/log:/mosquitto/log
