# ====================================================================
# RABBITMQ
# ====================================================================
# Connection String:  
# ====================================================================
services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'    
    hostname: messages
    network_mode: host
    restart: unless-stopped    
    environment:
      - TZ=America/Chicago
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=Test123!
    ports:
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    volumes:
      - ./volumes/data/:/var/lib/rabbitmq/mnesia
      - ./volumes/log/:/var/log/rabbitmq/    
      - ./plugins.conf:/etc/rabbitmq/enabled_plugins
