# ====================================================================
# MSSQL
# ====================================================================
# Connection String:  Server=localhost;Database=test;User Id=sa;Password=Test123!;TrustServerCertificate=True
# ====================================================================
services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    container_name: mssql
    restart: unless-stopped
    ports:
      - 1433:1433
    environment:
      - TZ=America/Chicago
      - MSSQL_SA_PASSWORD=Test123!
      - ACCEPT_EULA=Y
    volumes:      
      - ./volumes/backup:/var/opt/mssql/backup

# https://hub.docker.com/_/microsoft-mssql-server
# https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment?view=sql-server-ver16&pivots=cs1-bash