#########################################
# MSSQL
#########################################
services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    container_name: mssql
    restart: unless-stopped
    ports:
      - 1433:1433
    environment:
      TZ: America/Chicago
      MSSQL_SA_PASSWORD: SSoftware7!
      ACCEPT_EULA: Y
    volumes:      
      - ./volumes/backup:/var/opt/mssql/backup

# https://hub.docker.com/_/microsoft-mssql-server
# https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment?view=sql-server-ver16&pivots=cs1-bash