# ====================================================================
# POSTGRESQL
# ====================================================================
# Connection String:  Server=localhost;Port=5432;Database=test;User Id=user;Password=Test123!;
# ====================================================================
services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    restart: unless-stopped
    ports:
       - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "user" ]
      timeout: 45s
      interval: 10s
      retries: 10    
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=Test123!
      - PGDATA=/var/lib/postgresql/data/pgdata    
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
