#########################################
# MongoDB
#########################################
version: "3.7"

services:

  mongo:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmos
    restart: always
    ports:
    - '8081:8081'
    - '10250-10255:10250-10255'
    environment:
      TZ: America/Chicago      
    volumes:      
    - ./volumes/data/db:/data/db
    
  # Connection String: AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;

