# ====================================================================
# Azurite - Azure Storage Emlator
# ====================================================================
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    restart: unless-stopped
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    environment:
      - TZ=America/Chicago
    volumes:      
      - ./volumes/data:/data
