# ====================================================================
# MongoDB
# ====================================================================
# Connection String:  mongodb://user:Test123!@localhost:27017/
# ====================================================================
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - TZ=America/Chicago
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=Test123!
    volumes:      
      - ./volumes/data/db:/data/db
